using NpgsqlTypes;

namespace Mimir.Server.Storage.Entities;

/// <summary>
/// Spec §3: a single captured occurrence inside an Episode. Payloads are stored truncated per §4
/// with the original size recorded; <see cref="Tsv"/> is a stored generated column feeding the
/// Episode FTS leg of <c>mimir_search</c> (Events carry no embeddings in v1).
/// </summary>
public sealed class Event
{
    public Guid Id { get; set; }

    public Guid EpisodeId { get; set; }

    /// <summary>Arrival order within the Episode, from 1. Unique per Episode.</summary>
    public int Seq { get; set; }

    public EventType Type { get; set; }

    public DateTimeOffset At { get; set; }

    /// <summary>The hook's stdin JSON, truncated per §4 (jsonb).</summary>
    public required string Payload { get; set; }

    /// <summary>UTF-8 size of the payload before truncation.</summary>
    public int PayloadFullSize { get; set; }

    /// <summary>Explicit salience (§3): true only for <see cref="EventType.Remember"/>.</summary>
    public bool Salient { get; set; }

    /// <summary>Generated by Postgres over the payload's text; never written by the app.</summary>
    public NpgsqlTsVector? Tsv { get; set; }
}

/// <summary>
/// The closed §3 Event enum. Session start and end are deliberately absent: they are not Events —
/// SessionStart creates or resumes the Episode, SessionEnd Seals it (fields on Episode).
/// </summary>
public enum EventType
{
    UserPromptSubmit,
    PostToolUse,
    Stop,
    Remember,
}
