using NpgsqlTypes;
using Pgvector;

namespace Mimir.Server.Storage.Entities;

/// <summary>
/// Spec §3: one durable, reusable memory — the tier every Recall lane reads. Only the Merge Gate
/// writes new rows (§6); <see cref="Text"/> is the current version, with the full chain kept as
/// <see cref="WisdomVersion"/> rows. Retired Wisdom is excluded from all Recall and default search.
/// </summary>
public sealed class Wisdom
{
    public Guid Id { get; set; }

    public WisdomKind Kind { get; set; }

    /// <summary>
    /// The §3 <c>scope</c>: a Project id, with <c>Global</c> represented by the reserved
    /// <see cref="Project.GlobalId"/> pseudo-project.
    /// </summary>
    public Guid ScopeProjectId { get; set; }

    /// <summary>The current version's text; prior texts live in the version chain.</summary>
    public required string Text { get; set; }

    /// <summary>qwen3-embedding:0.6b over <see cref="Text"/> — 1024 dims (§6).</summary>
    public required Vector Embedding { get; set; }

    /// <summary>Generated by Postgres over <see cref="Text"/>; never written by the app.</summary>
    public NpgsqlTsVector? Tsv { get; set; }

    /// <summary>How many times the gate has confirmed this Wisdom; 1 at birth.</summary>
    public int Reinforcement { get; set; }

    public DateTimeOffset LastConfirmedAt { get; set; }

    /// <summary>Set by adjudication on contradiction (§6.4); cleared after 14 days.</summary>
    public DateTimeOffset? ContestedAt { get; set; }

    /// <summary>Retired = excluded from recall and default search, reversibly (§10).</summary>
    public DateTimeOffset? RetiredAt { get; set; }

    /// <summary>The Wisdom that superseded this one (§6.4); set together with retirement.</summary>
    public Guid? SupersededBy { get; set; }
}

/// <summary>The closed §3 kind enum.</summary>
public enum WisdomKind
{
    Fact,
    Preference,
    Lesson,
    Procedure,
}
