// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mimir.Server.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Mimir.Server.Storage.Migrations
{
    [DbContext(typeof(MimirDbContext))]
    [Migration("20260720054514_HarvestSchema")]
    partial class HarvestSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cwd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cwd");

                    b.Property<string>("Distillation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("distillation");

                    b.Property<DateTimeOffset?>("DistilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("distilled_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SealReason")
                        .HasColumnType("text")
                        .HasColumnName("seal_reason");

                    b.Property<DateTimeOffset?>("SealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sealed_at");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("PayloadFullSize")
                        .HasColumnType("integer")
                        .HasColumnName("payload_full_size");

                    b.Property<bool>("Salient")
                        .HasColumnType("boolean")
                        .HasColumnName("salient");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<NpgsqlTsVector>("Tsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("tsv")
                        .HasComputedColumnSql("jsonb_to_tsvector('english', payload, '[\"string\"]')", true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tsv"), "gin");

                    b.HasIndex("EpisodeId", "Seq")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.HarvestedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset?>("GoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gone_at");

                    b.Property<DateTimeOffset>("LastChanged")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.HasIndex("ProjectId");

                    b.ToTable("harvested_items", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity");

                    b.PrimitiveCollection<string[]>("RootPaths")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("root_paths");

                    b.HasKey("Id");

                    b.HasIndex("Identity")
                        .IsUnique();

                    b.HasIndex("RootPaths");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RootPaths"), "gin");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayName = "Global",
                            Identity = "mimir:global",
                            RootPaths = new string[0]
                        });
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Episode", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Event", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.HarvestedItem", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
