// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mimir.Server.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace Mimir.Server.Storage.Migrations
{
    [DbContext(typeof(MimirDbContext))]
    partial class MimirDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cwd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cwd");

                    b.Property<string>("Distillation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("distillation");

                    b.Property<DateTimeOffset?>("DistillationStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("distillation_started_at");

                    b.Property<DateTimeOffset?>("DistilledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("distilled_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SealReason")
                        .HasColumnType("text")
                        .HasColumnName("seal_reason");

                    b.Property<DateTimeOffset?>("SealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sealed_at");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("Distillation")
                        .HasFilter("sealed_at IS NOT NULL AND distillation <> 'Done'");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("PayloadFullSize")
                        .HasColumnType("integer")
                        .HasColumnName("payload_full_size");

                    b.Property<bool>("Salient")
                        .HasColumnType("boolean")
                        .HasColumnName("salient");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<NpgsqlTsVector>("Tsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("tsv")
                        .HasComputedColumnSql("jsonb_to_tsvector('english', payload, '[\"string\"]')", true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tsv"), "gin");

                    b.HasIndex("EpisodeId", "Seq")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.GoldenCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedFromInjectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_from_injection_id");

                    b.Property<Guid>("ExpectedWisdomId")
                        .HasColumnType("uuid")
                        .HasColumnName("expected_wisdom_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("QueryContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_context");

                    b.HasKey("Id");

                    b.HasIndex("CreatedFromInjectionId")
                        .IsUnique()
                        .HasFilter("created_from_injection_id IS NOT NULL");

                    b.HasIndex("ExpectedWisdomId");

                    b.HasIndex("ProjectId");

                    b.ToTable("golden_cases", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.HarvestedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("converted_at");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset?>("GoneAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gone_at");

                    b.Property<DateTimeOffset>("LastChanged")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("ConvertedAt")
                        .HasFilter("converted_at IS NULL");

                    b.HasIndex("Path");

                    b.HasIndex("ProjectId");

                    b.ToTable("harvested_items", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Injection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<int>("Chars")
                        .HasColumnType("integer")
                        .HasColumnName("chars");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lane");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("QueryContext")
                        .HasColumnType("text")
                        .HasColumnName("query_context");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("Verdict")
                        .HasColumnType("text")
                        .HasColumnName("verdict");

                    b.Property<DateTimeOffset?>("VerdictAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verdict_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SessionId");

                    b.ToTable("injections", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity");

                    b.PrimitiveCollection<string[]>("RootPaths")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("root_paths");

                    b.HasKey("Id");

                    b.HasIndex("Identity")
                        .IsUnique();

                    b.HasIndex("RootPaths");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RootPaths"), "gin");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DisplayName = "Global",
                            Identity = "mimir:global",
                            RootPaths = new string[0]
                        });
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Provenance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("episode_id");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("HarvestedItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("harvested_item_id");

                    b.Property<Guid>("WisdomId")
                        .HasColumnType("uuid")
                        .HasColumnName("wisdom_id");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("EventId");

                    b.HasIndex("HarvestedItemId");

                    b.HasIndex("WisdomId");

                    b.ToTable("provenance", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Wisdom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ContestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contested_at");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("LastConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_confirmed_at");

                    b.Property<int>("Reinforcement")
                        .HasColumnType("integer")
                        .HasColumnName("reinforcement");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<Guid>("ScopeProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_project_id");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<NpgsqlTsVector>("Tsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("tsv")
                        .HasComputedColumnSql("to_tsvector('english', text)", true);

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("ScopeProjectId");

                    b.HasIndex("SupersededBy");

                    b.HasIndex("Tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tsv"), "gin");

                    b.ToTable("wisdom", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.WisdomVersion", b =>
                {
                    b.Property<Guid>("WisdomId")
                        .HasColumnType("uuid")
                        .HasColumnName("wisdom_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cause");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("WisdomId", "Version");

                    b.ToTable("wisdom_versions", (string)null);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Episode", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Event", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.GoldenCase", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Injection", null)
                        .WithMany()
                        .HasForeignKey("CreatedFromInjectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mimir.Server.Storage.Entities.Wisdom", null)
                        .WithMany()
                        .HasForeignKey("ExpectedWisdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mimir.Server.Storage.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.HarvestedItem", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Injection", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Mimir.Server.Storage.Entities.InjectionItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("InjectionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double>("Score");

                            b1.Property<Guid>("WisdomId");

                            b1.HasKey("InjectionId", "__synthesizedOrdinal");

                            b1.ToTable("injections");

                            b1
                                .ToJson("items")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InjectionId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Provenance", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Episode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mimir.Server.Storage.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mimir.Server.Storage.Entities.HarvestedItem", null)
                        .WithMany()
                        .HasForeignKey("HarvestedItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mimir.Server.Storage.Entities.Wisdom", null)
                        .WithMany()
                        .HasForeignKey("WisdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.Wisdom", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ScopeProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mimir.Server.Storage.Entities.Wisdom", null)
                        .WithMany()
                        .HasForeignKey("SupersededBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Mimir.Server.Storage.Entities.WisdomVersion", b =>
                {
                    b.HasOne("Mimir.Server.Storage.Entities.Wisdom", null)
                        .WithMany()
                        .HasForeignKey("WisdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
